# Generated by Django 4.1.3 on 2022-11-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updated_at',
        ),
    ]
