# Generated by Django 4.1.3 on 2022-11-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stock_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='owner',
        ),
    ]
